// Generated by Hive CE
// Do not modify
// Check in to version control

import 'package:hive_ce/hive_ce.dart';
import 'package:my_eyes/data/models/eye_measurement_model.dart';
import 'package:my_eyes/data/models/eyewear_item_model.dart';
import 'package:my_eyes/data/models/prescription_model.dart';
import 'package:my_eyes/data/models/user_profile_model.dart';

extension HiveRegistrar on HiveInterface {
  void registerAdapters() {
    registerAdapter(EyeMeasurementModelAdapter());
    registerAdapter(EyewearItemModelAdapter());
    registerAdapter(PrescriptionModelAdapter());
    registerAdapter(UserProfileModelAdapter());
  }
}

extension IsolatedHiveRegistrar on IsolatedHiveInterface {
  void registerAdapters() {
    registerAdapter(EyeMeasurementModelAdapter());
    registerAdapter(EyewearItemModelAdapter());
    registerAdapter(PrescriptionModelAdapter());
    registerAdapter(UserProfileModelAdapter());
  }
}
